import React, { useState, useEffect, useMemo, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { 
  Plus, X, Activity, LogOut, ShieldCheck, FileText, AlertCircle, List, 
  ChevronRight, Loader2, MessageCircle, Globe, Box, Settings, Download,
  Cloud, CloudUpload, History, Database, Link, CheckCircle2, Wifi, WifiOff,
  User, Trash2, Edit3, Calendar, Shield, ExternalLink, Copy, Terminal,
  QrCode, Share2, Scan, Smartphone
} from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

// --- Supabase Config ---
const SUPABASE_URL = 'https://lnwiqirwjeeeahsjgzwg.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxud2lxaXJ3amVlZWFoc2pnendnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NTM0NTIsImV4cCI6MjA4NTQyOTQ1Mn0.t0Bv0CBl5CSrFe3VVaUNJXsnvtIN1sJ5y6J7tRTgWE0';
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// --- SQL Script (Added Config Table) ---
const SETUP_SQL = `-- 1. 资源链接表
CREATE TABLE IF NOT EXISTS links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  type TEXT CHECK (type IN ('tools', 'internal', 'external')),
  icon_name TEXT DEFAULT 'Globe',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 会员管理表
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wechat_name TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  status BOOLEAN DEFAULT TRUE,
  start_date DATE DEFAULT CURRENT_DATE,
  end_date DATE DEFAULT (CURRENT_DATE + INTERVAL '1 year'),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 系统配置表 (用于微信 AppID 等)
CREATE TABLE IF NOT EXISTS system_config (
  key TEXT PRIMARY KEY,
  value TEXT,
  description TEXT
);

INSERT INTO system_config (key, value, description) 
VALUES 
('wechat_appid', '', '微信开放平台 AppID'),
('wechat_redirect_uri', '', '授权回调域名 (需与开放平台一致)')
ON CONFLICT (key) DO NOTHING;`;

// --- Components ---

const WeChatOfficialAuth = ({ appId, redirectUri }: { appId: string, redirectUri: string }) => {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!appId || !containerRef.current || !(window as any).WxLogin) return;

    containerRef.current.innerHTML = '';
    
    new (window as any).WxLogin({
      self_redirect: false,
      id: "wechat_login_container",
      appid: appId,
      scope: "snsapi_login",
      redirect_uri: encodeURIComponent(redirectUri),
      state: Math.random().toString(36).substring(7),
      style: "black",
      href: ""
    });
  }, [appId, redirectUri]);

  if (!appId) {
    return (
      <div className="flex flex-col items-center justify-center p-12 bg-stone-50 rounded-3xl border border-dashed border-stone-200">
        <AlertCircle className="text-stone-300 mb-4" size={48} />
        <p className="text-stone-400 text-sm font-bold">微信 AppID 未配置</p>
        <p className="text-stone-400 text-[10px] mt-2 text-center uppercase tracking-widest leading-relaxed">请进入管理员后台<br/>设置微信开放平台参数</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center">
      <div id="wechat_login_container" ref={containerRef} className="bg-white rounded-3xl shadow-xl overflow-hidden min-h-[400px]">
      </div>
      <div className="mt-4 flex items-center gap-2 text-[10px] font-black text-emerald-600 uppercase tracking-widest">
         <Smartphone size={12} /> 官方安全登录
      </div>
    </div>
  );
};

const Modal = ({ isOpen, onClose, title, children, maxWidth = "max-w-2xl" }: any) => {
  if (!isOpen) return null;
  return (
    <div className="fixed inset-0 bg-stone-900/60 flex items-center justify-center z-50 p-4 backdrop-blur-md animate-in fade-in duration-300">
      <div className={`bg-white rounded-3xl shadow-2xl ${maxWidth} w-full overflow-hidden max-h-[90vh] flex flex-col border border-stone-200 animate-in zoom-in-95 duration-300`}>
        <div className="flex justify-between items-center p-6 border-b border-stone-100 glass sticky top-0 z-10">
          <h3 className="text-xl font-bold text-stone-800 tracking-tight">{title}</h3>
          <button onClick={onClose} className="text-stone-400 hover:text-stone-900 p-2 rounded-full hover:bg-stone-50"><X size={20} /></button>
        </div>
        <div className="p-8 overflow-y-auto bg-stone-50/50 flex-grow">{children}</div>
      </div>
    </div>
  );
};

// --- Main App ---

const App = () => {
  const [user, setUser] = useState({ isLoggedIn: false, username: 'Guest', isAdmin: false });
  const [links, setLinks] = useState<any[]>([]);
  const [members, setMembers] = useState<any[]>([]);
  const [config, setConfig] = useState<Record<string, string>>({});
  const [dbStatus, setDbStatus] = useState<'connected' | 'error' | 'testing'>('testing');
  const [showLogin, setShowLogin] = useState(false);
  const [showAdmin, setShowAdmin] = useState(false);
  const [adminTab, setAdminTab] = useState<'links' | 'members' | 'system'>('links');
  const [loading, setLoading] = useState(true);
  const [logoClicks, setLogoClicks] = useState(0);

  // Editing state
  const [editingLink, setEditingLink] = useState<any | null>(null);

  const fetchData = async () => {
    setLoading(true);
    const { data: linkData } = await supabase.from('links').select('*').order('id', { ascending: true });
    if (linkData) setLinks(linkData);
    
    const { data: configData } = await supabase.from('system_config').select('*');
    if (configData) {
      const configMap: any = {};
      configData.forEach(c => configMap[c.key] = c.value);
      setConfig(configMap);
    }

    const { data: memberData } = await supabase.from('members').select('*').order('created_at', { ascending: false });
    if (memberData) setMembers(memberData);

    setLoading(false);
  };

  const checkAuthCode = async () => {
    const params = new URLSearchParams(window.location.search);
    const code = params.get('code');
    if (code) {
      alert('已成功捕获微信授权 Code: ' + code + '\n演示登录中...');
      setUser({ isLoggedIn: true, username: '微信授权会员', isAdmin: false });
      window.history.replaceState({}, document.title, window.location.pathname);
    }
  };

  useEffect(() => {
    fetchData();
    checkAuthCode();
    supabase.from('links').select('count', { head: true }).then(({error}) => setDbStatus(error ? 'error' : 'connected'));
  }, []);

  const handleAdminLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    const fd = new FormData(e.target as HTMLFormElement);
    if (fd.get('u') === 'pmlaogao' && fd.get('p') === '011348') {
      setUser({ isLoggedIn: true, username: '超级管理员', isAdmin: true });
      setShowLogin(false);
    } else {
      alert('管理授权失败');
    }
  };

  const updateConfig = async (key: string, value: string) => {
    const { error } = await supabase.from('system_config').update({ value }).eq('key', key);
    if (!error) fetchData();
  };

  const handleCopySQL = () => {
    navigator.clipboard.writeText(SETUP_SQL);
    alert('SQL 已复制，请前往 Supabase 执行');
  };

  const deleteLink = async (id: any) => {
    if (!confirm('确定要删除这个链接吗？')) return;
    const { error } = await supabase.from('links').delete().eq('id', id);
    if (!error) fetchData();
    else alert('删除失败');
  };

  const saveLink = async (e: React.FormEvent) => {
    e.preventDefault();
    const fd = new FormData(e.target as HTMLFormElement);
    const payload = {
      title: fd.get('title'),
      url: fd.get('url'),
      description: fd.get('description'),
      type: fd.get('type'),
      icon_name: fd.get('icon_name') || 'Globe'
    };

    let error;
    if (editingLink?.id) {
      const { error: err } = await supabase.from('links').update(payload).eq('id', editingLink.id);
      error = err;
    } else {
      const { error: err } = await supabase.from('links').insert([payload]);
      error = err;
    }

    if (!error) {
      setEditingLink(null);
      fetchData();
    } else {
      alert('保存失败: ' + error.message);
    }
  };

  const deleteMember = async (id: any) => {
    if (!confirm('确定要删除该会员吗？')) return;
    const { error } = await supabase.from('members').delete().eq('id', id);
    if (!error) fetchData();
    else alert('删除失败');
  };

  return (
    <div className="min-h-screen flex flex-col pb-20">
      <nav className="fixed w-full z-40 top-0 glass border-b border-stone-200/50">
        <div className="max-w-7xl mx-auto px-6 h-16 sm:h-20 flex justify-between items-center">
          <div onClick={() => { setLogoClicks(c => c + 1); if(logoClicks + 1 >= 5) { setShowAdmin(true); setLogoClicks(0); } }} className="flex items-center gap-3 cursor-pointer group">
            <div className="w-10 h-10 bg-gradient-to-br from-amber-400 to-orange-600 rounded-xl flex items-center justify-center text-white font-black text-xl shadow-lg ring-2 ring-white transform group-active:scale-95 transition-all">P</div>
            <span className="font-black text-xl tracking-tighter text-stone-800">产品老高</span>
          </div>

          <div className="flex items-center gap-4">
            {user.isLoggedIn ? (
              <div className="flex items-center gap-2 bg-stone-100 p-1 rounded-full pl-4 border border-stone-200">
                <span className="font-bold text-xs text-stone-700">{user.username}</span>
                {user.isAdmin && <button onClick={() => setShowAdmin(true)} className="p-2 hover:bg-white rounded-full"><Settings size={18} /></button>}
                <button onClick={() => setUser({isLoggedIn:false, username:'Guest', isAdmin:false})} className="p-2 hover:bg-white rounded-full"><LogOut size={16} /></button>
              </div>
            ) : (
              <button onClick={() => setShowLogin(true)} className="px-6 py-2.5 bg-stone-900 text-white text-sm font-bold rounded-full shadow-xl hover:bg-stone-800 transition-all active:scale-95">
                微信登录
              </button>
            )}
          </div>
        </div>
      </nav>

      <header className="pt-32 pb-16 px-6 max-w-4xl mx-auto text-center">
        <div className="inline-block mb-4 px-4 py-1.5 rounded-full bg-emerald-50 border border-emerald-100 text-emerald-600 text-[10px] font-black uppercase tracking-[0.2em]">
          Official WeChat Auth System
        </div>
        <h1 className="text-5xl sm:text-7xl font-black text-stone-900 mb-8 tracking-tighter leading-none">
          探索 <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-500 to-emerald-700">AI 产品</span> 的边界
        </h1>
        <p className="text-stone-500 text-lg font-medium max-w-2xl mx-auto leading-relaxed">
          真实对接腾讯微信开放平台，扫码即刻开启智能资源库。<br/>精选工具，云端同步，助您重塑产品力。
        </p>
      </header>

      <main className="max-w-7xl mx-auto px-6 w-full">
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[1,2,3].map(i => <div key={i} className="h-64 bg-stone-100 rounded-3xl animate-pulse"></div>)}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {links.map(l => (
              <div key={l.id} onClick={() => window.open(l.url, '_blank')} className="group bg-white rounded-3xl p-8 border border-stone-100 shadow-sm hover:shadow-2xl transition-all cursor-pointer hover:-translate-y-1">
                 <div className="mb-6 w-14 h-14 bg-stone-50 rounded-2xl flex items-center justify-center text-stone-400 group-hover:bg-stone-900 group-hover:text-white transition-all">
                    {l.icon_name === 'Box' ? <Box size={28} /> : l.icon_name === 'Globe' ? <Globe size={28} /> : <FileText size={28} />}
                 </div>
                 <h3 className="text-xl font-bold text-stone-800 mb-3">{l.title}</h3>
                 <p className="text-stone-500 text-sm leading-relaxed mb-6 line-clamp-2 font-medium">{l.description}</p>
                 <div className="flex items-center text-xs font-black uppercase text-emerald-600">
                    立即访问 <ExternalLink size={14} className="ml-1" />
                 </div>
              </div>
            ))}
          </div>
        )}
      </main>

      {/* Admin Panel */}
      <Modal isOpen={showAdmin} onClose={() => setShowAdmin(false)} title="系统设置与授权管理" maxWidth="max-w-5xl">
        <div className="flex bg-stone-100 p-1.5 rounded-2xl mb-8">
          <button onClick={() => setAdminTab('links')} className={`flex-1 py-3 rounded-xl font-black text-xs uppercase transition-all ${adminTab === 'links' ? 'bg-white shadow-md text-stone-900' : 'text-stone-400'}`}>链接管理</button>
          <button onClick={() => setAdminTab('members')} className={`flex-1 py-3 rounded-xl font-black text-xs uppercase transition-all ${adminTab === 'members' ? 'bg-white shadow-md text-stone-900' : 'text-stone-400'}`}>会员管理</button>
          <button onClick={() => setAdminTab('system')} className={`flex-1 py-3 rounded-xl font-black text-xs uppercase transition-all ${adminTab === 'system' ? 'bg-white shadow-md text-stone-900' : 'text-stone-400'}`}>微信配置</button>
        </div>

        {adminTab === 'links' && (
          <div className="space-y-6 animate-in fade-in duration-300">
             <div className="flex justify-between items-center px-2">
                <h4 className="text-sm font-black text-stone-400 uppercase tracking-widest">资源链接列表 ({links.length})</h4>
                <button 
                  onClick={() => setEditingLink({ title: '', url: '', description: '', type: 'tools', icon_name: 'Globe' })}
                  className="px-4 py-2 bg-stone-900 text-white text-xs font-bold rounded-xl hover:bg-stone-800 transition-all flex items-center gap-2"
                >
                  <Plus size={14} /> 新增链接
                </button>
             </div>
             
             <div className="grid grid-cols-1 gap-3">
                {links.map(l => (
                  <div key={l.id} className="bg-white p-4 rounded-2xl border border-stone-100 flex items-center justify-between group">
                    <div className="flex items-center gap-4">
                      <div className="w-10 h-10 bg-stone-50 rounded-xl flex items-center justify-center text-stone-400">
                        {l.icon_name === 'Box' ? <Box size={18} /> : <Globe size={18} />}
                      </div>
                      <div>
                        <p className="font-bold text-stone-800 text-sm">{l.title}</p>
                        <p className="text-[10px] text-stone-400 truncate max-w-[200px]">{l.url}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button onClick={() => setEditingLink(l)} className="p-2 text-stone-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all"><Edit3 size={16}/></button>
                      <button onClick={() => deleteLink(l.id)} className="p-2 text-stone-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-all"><Trash2 size={16}/></button>
                    </div>
                  </div>
                ))}
             </div>
          </div>
        )}
        
        {adminTab === 'members' && (
          <div className="space-y-6 animate-in fade-in duration-300">
             <div className="flex justify-between items-center px-2">
                <h4 className="text-sm font-black text-stone-400 uppercase tracking-widest">会员授权列表 ({members.length})</h4>
             </div>
             <div className="overflow-x-auto bg-white rounded-3xl border border-stone-100 shadow-sm">
                <table className="w-full text-left text-sm">
                  <thead className="bg-stone-50 text-[10px] font-black text-stone-400 uppercase tracking-widest">
                    <tr>
                      <th className="p-4">微信名</th>
                      <th className="p-4">到期时间</th>
                      <th className="p-4">状态</th>
                      <th className="p-4">操作</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-stone-50">
                    {members.map(m => (
                      <tr key={m.id} className="hover:bg-stone-50/50 transition-colors">
                        <td className="p-4 font-bold text-stone-800">{m.wechat_name}</td>
                        <td className="p-4 text-stone-400 text-xs">{m.end_date}</td>
                        <td className="p-4">
                           <span className={`px-2 py-1 rounded-full text-[10px] font-black uppercase ${m.status ? 'bg-emerald-100 text-emerald-600' : 'bg-rose-100 text-rose-600'}`}>
                              {m.status ? '正常' : '禁用'}
                           </span>
                        </td>
                        <td className="p-4">
                           <button onClick={() => deleteMember(m.id)} className="p-2 text-stone-300 hover:text-rose-600 transition-colors">
                              <Trash2 size={16} />
                           </button>
                        </td>
                      </tr>
                    ))}
                    {members.length === 0 && (
                      <tr>
                        <td colSpan={4} className="p-12 text-center text-stone-400 text-xs italic">暂无会员数据</td>
                      </tr>
                    )}
                  </tbody>
                </table>
             </div>
          </div>
        )}

        {adminTab === 'system' && (
          <div className="space-y-8 animate-in fade-in duration-300">
             <div className="bg-emerald-50 p-6 rounded-3xl border border-emerald-100 shadow-inner">
                <h4 className="flex items-center gap-2 text-emerald-800 font-bold mb-2"><ShieldCheck size={18}/> 微信开放平台配置</h4>
                <p className="text-emerald-600/70 text-xs mb-6">请正确配置 AppID 和重定向地址，否则二维码无法渲染。</p>
                <div className="space-y-4">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1">AppID</label>
                    <input 
                      className="w-full p-4 bg-white rounded-2xl outline-none focus:ring-2 focus:ring-emerald-500 border border-emerald-100 text-stone-800 font-medium" 
                      placeholder="wxd930ea5d5a258f4f"
                      defaultValue={config.wechat_appid}
                      onBlur={(e) => updateConfig('wechat_appid', e.target.value)}
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1">Redirect URI (授权回调地址)</label>
                    <input 
                      className="w-full p-4 bg-white rounded-2xl outline-none focus:ring-2 focus:ring-emerald-500 border border-emerald-100 text-stone-800 font-medium" 
                      placeholder="https://example.com/auth"
                      defaultValue={config.wechat_redirect_uri}
                      onBlur={(e) => updateConfig('wechat_redirect_uri', e.target.value)}
                    />
                  </div>
                </div>
             </div>

             <div className="space-y-4">
               <div className="flex justify-between items-center px-1">
                 <span className="text-xs font-black text-stone-400 uppercase tracking-widest flex items-center gap-2"><Terminal size={14}/> 数据库初始化 SQL</span>
                 <button onClick={handleCopySQL} className="text-xs font-bold text-emerald-600 hover:text-emerald-700 flex items-center gap-1"><Copy size={12}/> 复制脚本</button>
               </div>
               <pre className="bg-stone-900 text-emerald-500 p-6 rounded-3xl font-mono text-[11px] h-60 overflow-auto shadow-2xl leading-relaxed border border-stone-800">
                 {SETUP_SQL}
               </pre>
             </div>
          </div>
        )}
      </Modal>

      {/* Edit Link Modal */}
      <Modal isOpen={!!editingLink} onClose={() => setEditingLink(null)} title={editingLink?.id ? "编辑资源链接" : "添加新资源"}>
         <form onSubmit={saveLink} className="space-y-5">
            <div className="space-y-2">
               <label className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1">链接标题</label>
               <input name="title" defaultValue={editingLink?.title} required className="w-full p-4 bg-stone-50 border border-stone-200 rounded-2xl outline-none focus:ring-2 focus:ring-stone-900" />
            </div>
            <div className="space-y-2">
               <label className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1">URL 地址</label>
               <input name="url" defaultValue={editingLink?.url} required className="w-full p-4 bg-stone-50 border border-stone-200 rounded-2xl outline-none focus:ring-2 focus:ring-stone-900" />
            </div>
            <div className="grid grid-cols-2 gap-4">
               <div className="space-y-2">
                  <label className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1">分类</label>
                  <select name="type" defaultValue={editingLink?.type || 'tools'} className="w-full p-4 bg-stone-50 border border-stone-200 rounded-2xl outline-none focus:ring-2 focus:ring-stone-900 appearance-none">
                     <option value="tools">核心工具</option>
                     <option value="internal">内部实验</option>
                     <option value="external">精选外链</option>
                  </select>
               </div>
               <div className="space-y-2">
                  <label className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1">图标 (Lucide Name)</label>
                  <input name="icon_name" defaultValue={editingLink?.icon_name || 'Globe'} className="w-full p-4 bg-stone-50 border border-stone-200 rounded-2xl outline-none focus:ring-2 focus:ring-stone-900" placeholder="Globe / Box / FileText" />
               </div>
            </div>
            <div className="space-y-2">
               <label className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1">描述文案</label>
               <textarea name="description" defaultValue={editingLink?.description} required className="w-full p-4 bg-stone-50 border border-stone-200 rounded-2xl outline-none focus:ring-2 focus:ring-stone-900 h-24 resize-none" />
            </div>
            <button type="submit" className="w-full py-4 bg-stone-900 text-white rounded-2xl font-black shadow-xl hover:bg-stone-800 active:scale-95 transition-all">保存变更</button>
         </form>
      </Modal>

      {/* Login Modal */}
      <Modal isOpen={showLogin} onClose={() => setShowLogin(false)} title="腾讯微信授权登录">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          <div className="order-2 md:order-1 space-y-8">
            <div>
              <h4 className="text-2xl font-black text-stone-800 mb-2">官方安全授权</h4>
              <p className="text-stone-500 text-sm leading-relaxed font-medium">
                本站直接对接腾讯官方微信开放平台，无需注册，扫码确认即可完成登录并享有会员特权。
              </p>
            </div>

            <div className="space-y-4 pt-4 border-t border-stone-100">
              <p className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1 flex items-center gap-2"><ShieldCheck size={12}/> 管理员通道</p>
              <form onSubmit={handleAdminLogin} className="space-y-4">
                <input name="u" required className="w-full p-4 bg-stone-50 border border-stone-200 rounded-2xl outline-none focus:ring-2 focus:ring-stone-900 transition-all font-medium" placeholder="管理员账号" />
                <input name="p" type="password" required className="w-full p-4 bg-stone-50 border border-stone-200 rounded-2xl outline-none focus:ring-2 focus:ring-stone-900 transition-all font-medium" placeholder="管理授权码" />
                <button type="submit" className="w-full py-4 bg-stone-900 text-white rounded-2xl font-black hover:bg-stone-800 shadow-xl transition-all active:scale-95">管理员登录</button>
              </form>
            </div>
          </div>

          <div className="order-1 md:order-2 flex flex-col items-center">
            <WeChatOfficialAuth 
              appId={config.wechat_appid} 
              redirectUri={config.wechat_redirect_uri || window.location.origin} 
            />
            
            <p className="mt-6 text-[10px] text-stone-400 text-center font-bold leading-relaxed uppercase tracking-[0.2em]">
               使用微信扫一扫<br/>官方接口 · 隐私安全 · 极速授权
            </p>
          </div>
        </div>
      </Modal>

      <footer className="mt-auto py-12 text-center border-t border-stone-100 bg-white">
        <p className="font-black tracking-[0.3em] text-stone-800 text-sm uppercase">© {new Date().getFullYear()} 产品老高 - PM LAOGAO</p>
        <p className="text-stone-400 text-[10px] font-bold uppercase mt-2 tracking-widest">基于腾讯微信开放平台官方标准构建 | SUPABASE 后端支持</p>
      </footer>
    </div>
  );
};

// --- Entry Point ---
const rootEl = document.getElementById('root');
if (rootEl) {
  createRoot(rootEl).render(<App />);
}
